Fix aggregate response for zero connected commons
uc-cdis/workspace-token-service pull request #61
Opened 2023-07-03 22:16 UTC by nss10

in agg req

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2023-07-10 19:41 UTC, Avantol13 requested changes
Please add unit test(s) necessary to test this change in behavior

2023-07-10 19:41 UTC, Avantol13 commented on wts/tokens.py
>      Return:
docstring needs an update

2023-07-10 22:25 UTC, nss10 commented on wts/tokens.py
>      Return:
Updated.

2023-07-10 22:25 UTC, nss10 commented
> Please add unit test(s) necessary to test this change in behavior

Thank you. Unit tests added. @Avantol13

2023-07-12 14:52 UTC, paulineribeyre approved these changes

2023-07-12 18:05 UTC, merged